[package]
name = "git-rust"
version = "0.1.0"
authors = ["Shuhei <sh7916@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "git-rust"
path = "main.rs"
